# Generated by Django 2.2.7 on 2021-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.IntegerField()),
                ('question', models.CharField(max_length=200, null=True)),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('option3', models.CharField(max_length=200, null=True)),
                ('option4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, null=True)),
                ('scor', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('time', models.CharField(max_length=50, null=True)),
                ('total_quetion', models.IntegerField()),
            ],
        ),
    ]
