# Generated by Django 2.2.7 on 2021-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wrong',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
