# Generated by Django 2.2.7 on 2021-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='correct',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='total_quetion',
            field=models.CharField(max_length=10),
        ),
    ]
