# Generated by Django 2.2.7 on 2021-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210727_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='test_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
