# Generated by Django 2.2.7 on 2021-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, null=True)),
                ('test', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200, null=True)),
                ('correct_correct', models.CharField(max_length=200)),
                ('your_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='test_id',
            field=models.IntegerField(),
        ),
    ]
