# Generated by Django 2.2.7 on 2021-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210728_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizanswers',
            name='correct_answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userquizanswers',
            name='your_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
